//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GeoTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GEOTOOTYPE                  129
#define IDD_BRUSHES                     131
#define IDB_PIT_BRUSH                   135
#define IDB_PIT_BRUSH_BIG               139
#define IDD_SLOT_PROPERTIES             140
#define IDB_COLORPICKER                 143
#define IDB_DEFAULT                     144
#define IDD_PREVIEW                     145
#define IDD_SLOTS                       146
#define IDR_ACTION_MENU                 148
#define IDB_SHIFT                       152
#define IDB_SCALE                       153
#define IDB_PLANE                       154
#define IDD_INSTRUMENTS                 155
#define IDB_ARROW                       156
#define IDD_LOAD_MAP                    157
#define IDR_MODELMENU                   158
#define IDD_INDEXER_DIALOG              159
#define IDC_PIT_BRUSH                   1000
#define IDC_PIT_BRUSH_BIG               1001
#define IDC_TREE                        1001
#define IDC_ARROW_BUTTON                1003
#define IDC_STATIC_TEXTURE              1006
#define IDC_STATIC_LOCATION             1007
#define IDC_STATIC_FG                   1008
#define IDC_STATIC_BG                   1009
#define IDC_BUTTON_FG                   1010
#define IDC_BUTTON_BG                   1011
#define IDC_STATIC_SHIFT                1012
#define IDC_STATIC_SCALE                1013
#define IDC_EDIT_SHIFT_X                1014
#define IDC_EDIT_SHIFT_Y                1015
#define IDC_EDIT_SHIFT_Z                1016
#define IDC_EDIT_SCALE_X                1017
#define IDC_EDIT_SCALE_Y                1018
#define IDC_EDIT_SCALE_Z                1019
#define IDC_STATIC_SHIFT_X              1020
#define IDC_STATIC_SHIFT_Y              1021
#define IDC_STATIC_SHIFT_Z              1022
#define IDC_STATIC_FROM                 1023
#define IDC_STATIC_TO                   1024
#define IDC_EDIT_FROM_X                 1025
#define IDC_EDIT_FROM_Y                 1026
#define IDC_EDIT_FROM_Z                 1027
#define IDC_EDIT_TO_X                   1028
#define IDC_EDIT_TO_Y                   1029
#define IDC_EDIT_TO_Z                   1030
#define IDC_STATIC_FROM_X               1031
#define IDC_STATIC_FROM_Y               1032
#define IDC_STATIC_FROM_Z               1033
#define IDC_CHECK_BACK                  1034
#define IDC_STATIC_STEP                 1035
#define IDC_EDIT_STEP                   1036
#define IDC_STATIC_GRADATION            1037
#define IDC_EDIT_GRADATION              1038
#define IDC_STATIC_RING_COUNT           1039
#define IDC_STATIC_PLANE                1040
#define IDC_RADIO_PLANE_X               1041
#define IDC_RADIO_PLANE_Y               1042
#define IDC_RADIO_PLANE_Z               1043
#define IDC_STATIC_BRICK                1044
#define IDC_STATIC_GAP                  1045
#define IDC_STATIC_PLANE2               1046
#define IDC_RADIO_PLANE_X2              1047
#define IDC_RADIO_PLANE_Y2              1048
#define IDC_RADIO_PLANE_Z2              1049
#define IDC_STATIC_PERSISTENCE          1050
#define IDC_STATIC_OCTAVE_COUNT         1051
#define IDC_EDIT_PERSISTENCE            1052
#define IDC_PREVIEW                     1052
#define IDC_EDIT_OCTAVE_COUNT           1053
#define IDC_EDIT_BRICK_X                1054
#define IDC_EDIT_BRICK_Y                1055
#define IDC_EDIT_BRICK_Z                1056
#define IDC_EDIT_GAP_X                  1057
#define IDC_EDIT_GAP_Y                  1058
#define IDC_EDIT_GAP_Z                  1059
#define IDC_STATIC_BRICK_X              1060
#define IDC_STATIC_BRICK_Y              1061
#define IDC_STATIC_BRICK_Z              1062
#define IDC_STATIC_CENTER               1063
#define IDC_STATIC_RADIUS               1064
#define IDC_CHECK_IS_BRICK              1065
#define IDC_STATIC_NEAR_BOUND           1066
#define IDC_EDIT_NEAR_BOUND             1067
#define IDC_STATIC_FAR_BOUND            1068
#define IDC_EDIT_FAR_BOUND              1069
#define IDC_STATIC_LOCATION_PLANE       1070
#define IDC_RADIO_PLANE_LOCATION_Y      1071
#define IDC_RADIO_PLANE_LOCATION_Z      1072
#define IDC_RADIO_PLANE_LOCATION_X      1073
#define IDC_STATIC_FADE                 1074
#define IDC_EDIT_FADE                   1075
#define IDC_STATIC_FADING               1076
#define IDC_EDIT_FADING                 1077
#define IDC_PREVIEW_IMAGE               1078
#define IDC_STATIC_SHIFT_IMAGE          1079
#define IDC_STATIC_SCALE_IMAGE          1080
#define IDC_STATIC_PLANE_IMAGE          1081
#define IDC_STATIC_PLANE_IMAGE2         1082
#define IDC_EDIT_RADIUS                 1083
#define IDC_STATIC_PLANE_IMAGE3         1084
#define IDC_LIST2                       1086
#define IDC_EDIT_STEP_X                 1095
#define IDC_EDIT_STEP_Y                 1096
#define IDC_EDIT_STEP_Z                 1097
#define IDC_EDIT_TRESHOLD               1098
#define ID_LOAD_MAP                     32771
#define ID_PLANE_DAM_LOCAL              32772
#define ID_PLANE_DAM                    32773
#define ID_REMOVE_DAM                   32774
#define ID_REMOVE_DAM_LOCAL             32775
#define ID_PIT_BRUSH                    32776
#define ID_PIT_BRUSH_BIG                32777
#define ID_SHOW_BRUSHES                 32779
#define ID_SHOW_INSTRUMENTS             32779
#define ID_SHOW_SLOT_PROPERTIES         32782
#define ID_SHOW_PREVIEW                 32783
#define ID_SHOW_SLOTS                   32784
#define ID_REFRESH                      32785
#define ID_LOAD_TEXTURE                 32787
#define ID_SAVE_TEXTURE                 32788
#define ID_CLEAR_SLOT                   32789
#define ID_PAINTER_SLOT                 32790
#define ID_MIXER_SLOT                   32791
#define ID_DELETE_MODEL_TX              32792
#define ID_ADD_MODEL_TX                 32793
#define ID_BUTTON_TOGGLE_INDEXED        32794
#define ID_BTN_ZOOM                     32795
#define ID_BUTTONZERO                   32796
#define ID_PUBLISH                      32797
#define ID_BUTTON_ZSHIFT_PLUS           32798
#define ID_BUTTON_ZSHIFT_MINUS          32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
