#define BOOST_NO_CONFIG

#include "boost/preprocessor/config/config.hpp"

#define BOOST_NO_TEMPLATE_TEMPLATES
#define BOOST_MPL_NO_BIND_TEMPLATE
#define BOOST_NO_NON_TYPE_TEMPLATE_PARTIAL_SPECIALIZATION
#define BOOST_BROKEN_DEFAULT_TEMPLATE_PARAMETERS_IN_NESTED_TEMPLATES
#define BOOST_MPL_BROKEN_OVERLOAD_RESOLUTION
#define BOOST_EXTENDED_TEMPLATE_PARAMETERS_MATCHING
