#ifndef _UNIVERSE_INTERFACE_SUPPORT_
#define _UNIVERSE_INTERFACE_SUPPORT_

//General

#include "InterfaceLogic.h"

const uint32_t UNIVERSE_INTERFACE_MESSAGE_MASK = 0xFF;

enum terUniverseInterfaceMessage
{
    UNIVERSE_INTERFACE_MESSAGE_GAME_RESULT_UNDEFINED = 0,
	UNIVERSE_INTERFACE_MESSAGE_GAME_VICTORY = 1,
	UNIVERSE_INTERFACE_MESSAGE_GAME_DEFEAT = 2,
    UNIVERSE_INTERFACE_MESSAGE_ACTIVE = 1 << 15,
};

//------------------------------------

enum terInterfaceLegionModeType
{
	INTERFACE_LEGION_MODE_STOP = 1,
	INTERFACE_LEGION_MODE_ATTACK = 2,
	INTERFACE_LEGION_MODE_MOVE = 4,
	INTERFACE_LEGION_MODE_PATROL = 8,
	INTERFACE_LEGION_MODE_BACK_TO_FRAME = 16,
	INTERFACE_LEGION_MODE_EXCHANGE = 32,
	INTERFACE_LEGION_MODE_TARGET_BUILD = 64
};

extern int terShowTips;
 
#endif
