
//  Use, modification and distribution are subject to the 
//  Boost Software License, Version 1.0. (See accompanying file 
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

//  See http://www.boost.org/libs/config for the most recent version.

// Test file for macro BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL
// This file should compile, if it does not then
// BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL needs to be defined.
// see boost_no_using_breaks_adl.cxx for more details

// Do not edit this file, it was generated automatically by
// ../tools/generate from boost_no_using_breaks_adl.cxx on
// Wed Dec 10 13:13:32 GMTST 2003

// Must not have BOOST_ASSERT_CONFIG set; it defeats
// the objective of this file:
#ifdef BOOST_ASSERT_CONFIG
#  undef BOOST_ASSERT_CONFIG
#endif

#include <boost/config.hpp>
#include "test.hpp"

#ifndef BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL
#include "boost_no_using_breaks_adl.cxx"
#else
namespace boost_function_scope_using_declaration_breaks_adl = empty_boost;
#endif

int cpp_main( int, char *[] )
{
   return boost_function_scope_using_declaration_breaks_adl::test();
}  
   
