#!/bin/bash
set -e

if [[ -z "$DEPS_PREFIX" ]]; then
  DEPS_PREFIX=/usr
fi

# Download boost, untar, setup install with bootstrap and install
mkdir /opt/boost
cd /opt/boost
wget https://archives.boost.io/release/1.90.0/source/boost_1_90_0.tar.gz
tar xfvz boost_1_90_0.tar.gz
rm boost_1_90_0.tar.gz
cd boost_1_90_0
./bootstrap.sh --prefix=$DEPS_PREFIX
./b2 install --with-system --with-stacktrace

cd /opt
rm -rf /opt/boost
