ECHO	= /bin/echo

all: 
	@${ECHO} "<boost-root>/libs/iterator/doc/GNUmakefile should be replaced by"
	@${ECHO}
	@${ECHO} "    http://www.boost-consulting.com/writing/GNUmakefile,"
	@${ECHO}
	@${ECHO} "before proceeding.  That file is not included in the Boost"
	@${ECHO} "distribution because it is licensed under the GPL, which violates"
	@${ECHO} "Boost license requirements."

