//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EffectTool.rc
//
#define IDD_ABOUTBOX                    100
#define ID_TOOLBAR_SAVE                 101
#define IDD_FORMVIEW                    101
#define ID_TOOLBAR_SPRITE               102
#define IDR_MAINFRAME                   128
#define IDR_EFFECTTYPE                  129
#define IDS_CLOSEFRAMEDIRTY             129
#define IDR_MENU_POPUP                  130
#define IDD_LOAD_SPRITE                 135
#define IDR_TOOLBAR1                    136
#define IDD_ALPHA                       139
#define IDR_TOOLBAR_TOOLS               142
#define IDB_TREE                        144
#define IDC_CURSOR_MOVE                 145
#define ID_GROUP_NEW                    146
#define ID__DELETEGROUP                 147
#define ID_Menu                         148
#define ID_NEW_S                        149
#define ID_SET3DMODEL                   150
#define ID_SHOW3DMODEL                  151
#define ID_SET3DBACKGROUND              152
#define ID_SHOW3DBACKGROUND             153
#define IDD_OPTTREE                     154
#define IDR_TOOLBAR_OPT                 155
#define IDB_BITMAP1                     161
#define IDB_GRAPH_CHECKBOX              161
#define IDB_EMPTY_TEXTURE               162
#define IDC_COMBO_POS_TYPE              1000
#define IDC_COMBO_OUT_TYPE              1001
#define IDC_EMITTER_LIFE_TIME           1002
#define IDC_BROWSE                      1003
#define IDC_IMAGE                       1004
#define IDC_ALPHA                       1005
#define IDC_IMAGE_PLUME                 1006
#define IDC_EDIT_NPOINTS                1009
#define IDC_EDIT_TIME                   1010
#define IDC_COMBO_VEL_TYPE              1011
#define IDC_EDIT_PARTICLE_COUNT         1012
#define IDC_EDIT_SIZE                   1013
#define IDC_BUTTON_FORALL               1014
#define IDC_EDIT_SIZE_DELTA             1015
#define IDC_EDIT_VEL_DISP               1016
#define IDC_EDIT_TIME_DISP              1017
#define IDC_EDIT_GRAVITATION            1018
#define IDC_EDIT_ANG_VEL                1019
#define IDC_CHECK_SIZE                  1020
#define IDC_CHECK_GRAV                  1021
#define IDC_CHECK_ANG_VEL               1022
#define IDC_VIEW_MODE                   1023
#define IDC_EDIT_VEL_START              1023
#define IDC_COLORS                      1024
#define IDC_CHECK_VELOCITY              1025
#define IDC_SLIDER                      1026
#define IDC_COMBO_EMMITER_TYPE          1026
#define IDC_EDIT1                       1027
#define IDC_EDIT_SUR_ANGLE              1027
#define IDC_SAMPLE                      1028
#define IDC_EDIT_SUR_SIZE               1028
#define IDC_SLIDER_TIME                 1029
#define IDC_GRAPH                       1030
#define IDC_SHOW                        1031
#define IDC_EDIT_X                      1032
#define IDC_EDIT_Y                      1033
#define IDC_EDIT_Z                      1034
#define IDC_STATIC_X                    1035
#define IDC_STATIC_Y                    1036
#define IDC_STATIC_Z                    1037
#define IDC_STATIC_PARTICLE_COUNT       1038
#define IDC_STATIC_TIME_DISP            1039
#define IDC_STATIC_VEL_DISP             1040
#define IDC_STATIC_NPOINTS              1041
#define IDC_STATIC_TIME                 1042
#define IDC_STATIC_SIZE                 1043
#define IDC_STATIC_GRAVITATION          1044
#define IDC_STATIC_ANG_VEL              1045
#define IDC_STATIC_SIZE_DELTA           1046
#define IDC_STATIC_SUR_ANGLE            1047
#define IDC_STATIC_VEL_START            1048
#define IDC_CHECK_PLAY_CYCLED           1049
#define IDC_COMBO_SPLINE_ENDING         1050
#define IDC_CHECK_ANG_CHAOS             1051
#define IDC_GENERATE_PROLONGED          1052
#define IDC_STATIC_VEL_TYPE             1053
#define IDC_STATIC_GENERATION           1054
#define IDC_STATIC_VELOCITY             1055
#define IDC_STATIC_SPLINE_ENDING        1056
#define IDC_STATIC_PARTICLE             1057
#define IDC_STATIC_DESP                 1058
#define IDC_STATIC_GENERATION2          1059
#define IDC_STATIC_EMMITER_TYPE         1059
#define IDC_STATIC_EMITTER              1060
#define IDC_FPS                         1061
#define IDC_STATIC_SUR_SIZE             1061
#define IDC_CHECK_SHOW_GRID             1062
#define IDC_STATIC_SURFACE              1062
#define IDC_EDIT_SCALE                  1063
#define IDC_CHECK_SUR_PLANAR            1063
#define IDC_SET_SCALE                   1064
#define IDC_CHECK_SUR_CENTER            1064
#define IDC_CHECK_SHOW_WORLD            1065
#define IDC_CHECK_USE_FORCE_FIELD       1065
#define IDC_EDIT_RATE                   1066
#define IDC_EDIT_CUR_TIME               1066
#define IDC_RATE                        1067
#define IDC_USEL_LIGHT                  1067
#define IDC_CUSTOM1                     1068
#define IDC_STATIC_FPS                  1071
#define IDC_SPIN1                       1074
#define IDC_STATIC2                     1079
#define IDC_STATIC1                     1080
#define IDC_TRIANGLE_COUNT              1081
#define IDC_TRIANGLE_SQUARE             1082
#define ID_EFFECT_NEW                   32771
#define ID_ELEMENT_DELETE               32772
#define ID_EFFECT_EMITTER_NEW           32773
#define ID_EFFECT_EMITTER_DEL           32774
#define ID_TB_PAUSE                     32776
#define ID_TB_PLAY                      32777
#define ID_TB_NEXT                      32778
#define ID_TB_FIRST                     32779
#define ID_TB_LAST                      32780
#define ID_TOOLS_DIR                    32781
#define ID_TOOLS_POS                    32782
#define ID_TOOLBAR_OPEN                 32784
#define ID_TOOLS_BS_DIR                 32786
#define ID_TOOLS_BS_DIR_                32786
#define ID_TOOLBAR_EXPORT               32792
#define ID_TOOLBAR_SAVEALL              32793
#define ID_BUTTON32795                  32795
#define ID_BUT_ONE                      32800
#define ID_BUT_TWO                      32803
#define ID_BUTTON_FORALL                32810
#define ID_TOOLS_DIR_                   32811
#define ID_TOOLS_POS_                   32812
#define ID_BUTTON32813                  32813
#define ID_FULLSCREEN                   32816
#define ID_BUTTON32817                  32817
#define ID_FINDCENTER                   32818
#define ID_SPLINE_EDIT                  32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
