# Try to find DXVK Native libs and include paths.
# Once done this will define
#
# DXVK_Native_FOUND
# DXVK_NATIVE_INCLUDE_DIRS
# DXVK_NATIVE_LIBRARIES
#

SET(MSVC_YEAR_NAME)
IF (MSVC_VERSION GREATER 1599)		# >= 1600
    SET(MSVC_YEAR_NAME VS2010)
ELSEIF(MSVC_VERSION GREATER 1499)	# >= 1500
    SET(MSVC_YEAR_NAME VS2008)
ELSEIF(MSVC_VERSION GREATER 1399)	# >= 1400
    SET(MSVC_YEAR_NAME VS2005)
ELSEIF(MSVC_VERSION GREATER 1299)	# >= 1300
    SET(MSVC_YEAR_NAME VS2003)
ELSEIF(MSVC_VERSION GREATER 1199)	# >= 1200
    SET(MSVC_YEAR_NAME VS6)
ENDIF()

SET(DXVK_NATIVE_SEARCH_PATHS
    ${DXVK_NATIVE_SEARCH_PATHS}
    ${LIBRARY_SEARCH_PATHS}
    ../dxvk-native
    ../dxvk-native/build/src/d3d9
)

FIND_PATH(DXVK_NATIVE_INCLUDE_DIR
        NAMES native/directx/d3d9.h native/windows/windows.h
        HINTS
        $ENV{DXVK_NATIVE_DIR}
        $ENV{DXVK_NATIVE_PATH}
        PATH_SUFFIXES include
        PATHS ${DXVK_NATIVE_SEARCH_PATHS}
)

FIND_LIBRARY(DXVK_NATIVE_D3D9_LIBRARY
        NAMES dxvk_d3d9 libdxvk_d3d9 libdxvk_d3d9-0
        HINTS
        $ENV{DXVK_NATIVE_DIR}
        $ENV{DXVK_NATIVE_PATH}
        $ENV{DXVK_NATIVE_D3D9_DIR}
        $ENV{DXVK_NATIVE_D3D9_PATH}
        PATH_SUFFIXES lib lib64
        PATHS ${DXVK_NATIVE_SEARCH_PATHS}
)

SET(DXVK_NATIVE_LIBRARIES ${DXVK_NATIVE_D3D9_LIBRARY})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(DXVK_Native DEFAULT_MSG DXVK_NATIVE_INCLUDE_DIR)

set(DXVK_NATIVE_INCLUDE_DIRS "${DXVK_NATIVE_INCLUDE_DIR}/native/directx" "${DXVK_NATIVE_INCLUDE_DIR}/native/windows")

mark_as_advanced(DXVK_NATIVE_INCLUDE_DIR DXVK_NATIVE_D3D9_LIBRARY)

MESSAGE("DXVK Native includes: ${DXVK_NATIVE_INCLUDE_DIRS}")
MESSAGE("DXVK Native library: ${DXVK_NATIVE_LIBRARIES}")