#!/bin/bash
set -e

# Add backports to sources and update
echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
apt-get update

#Backport git version doesn't work properly
apt-get install -y git

# Install dependencies from backports to have latest
#ffmpeg / Perimeter deps
apt-get install -t buster-backports -y \
  lld \
  nasm \
  libstdc++6 \
  libsdl2-image-dev libsdl2-net-dev libsdl2-mixer-dev \
  libboost-dev \
  zlib1g-dev \
  libvorbis-dev \
  libvulkan-dev glslang-tools \
  build-essential \
  cmake meson ninja-build

#SDL2 deps
apt-get install -t buster-backports -y \
  pkg-config gnome-desktop-testing libasound2-dev libpulse-dev \
  libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
  libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
  libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
  libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev 
#libpipewire-0.3-dev libwayland-dev libdecor-0-dev
