#!/bin/bash
set -e

#Replace old system SDL2 with compiled version

git clone https://github.com/libsdl-org/SDL.git -b release-2.28.2 /opt/src/sdl
                                                                 
cd /opt/src/sdl

mkdir build
cd build

../configure --prefix=/opt/out/sdl

make
make install -j4

#Replace system SDL2 with ours
cp -va /opt/out/sdl/include/* /usr/include/
cp -va /opt/out/sdl/lib/* /usr/lib/x86_64-linux-gnu/
